### ISSUE TITLE
Successful DELETE still throws error

### ISSUE THREAD

**Issue by Dissgruntled** [SReject/JSON-For-Mirc#11]
Using this code:

```
alias unfollowchan {
  var %json followdel
  JSONOpen -duw %json https://api.twitch.tv/kraken/users/ $+ $lower($me) $+ /follows/channels/ $+ $lower($1)
  JSONUrlMethod %json DELETE
  JSONUrlHeader %json Connection close
  JSONUrlHeader %json Accept application/vnd.twitchtv.v3+json
  JSONUrlHeader %json Authorization OAuth $oauth
  JSONUrlGet %json
  if ($jsonerror) echo -s $json(%json).error
}
```

the object is successfully deleted but still gives the error

> Unable to Parse: Invalid JSON

**Comment by SReject** [comment]
Could you enable json debug (`/JSONDebug on`), run the command and give me the output

You may need to sensor your oauth token from the data.

**Comment by Paper0rPlastic** [comment]
Here you are:

[JSONForMirc] Calling /JSONOpen -duw followdel https://api.twitch.tv/kraken/users/p0pbot/follows/channels/happy_meal_toy
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="init")throw new Error("JSON handler not ready");url.u="https://api.twitch.tv/kraken/users/p0pbot/follows/channels/happy_meal_toy";status="url";return"1 OK"}catch(e){error=e.message;return"0 "+error}}());
[followdel] Successfully created
[JSONForMirc] Calling /JSONUrlMethod followdel DELETE
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.m="DELETE";return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlMethod] Method set to DELETE
[JSONForMirc] Calling /JSONUrlHeader followdel Connection close
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.h.push(["Connection","close"]);return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlHeader] Header 'Connection' set to close
[JSONForMirc] Calling /JSONUrlHeader followdel Accept application/vnd.twitchtv.v3+json
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.h.push(["Accept","application/vnd.twitchtv.v3+json"]);return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlHeader] Header 'Accept' set to application/vnd.twitchtv.v3+json
[JSONForMirc] Calling /JSONUrlHeader followdel Authorization OAuth MY_OAUTH_TOKEN
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.h.push(["Authorization","OAuth MY_OAUTH_TOKEN"]);return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlHeader] Header 'Authorization' set to OAuth MY_OAUTH_TOKEN
[JSONForMirc] Calling /JSONUrlGet followdel
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");json=parse(xhr());status="done";return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel] /JSONUrlGet - followdel --RAISED-- Unable to Parse: Invalid JSON
[JSONForMirc] /JSONClose followdel
[followdel] Closed

**Comment by SReject** [comment]
What does this echo

```
alias unfollowchan {
  var %json followdel
  JSONOpen -duw %json https://api.twitch.tv/kraken/users/ $+ $lower($me) $+ /follows/channels/ $+ $lower($1)
  JSONUrlMethod %json DELETE
  JSONUrlHeader %json Connection close
  JSONUrlHeader %json Accept application/vnd.twitchtv.v3+json
  JSONUrlHeader %json Authorization OAuth $oauth
  JSONUrlGet %json
  if ($jsonerror) {
    echo -s $json(%json).error
    
    var %get = response.responseText.substring(0,3500)
    echo -s >> $com(JSONHandler::followdel, eval, 1, bstr, %get) >> $com(JSONHandler::followdel).result
  }
}
```

**Comment by Paper0rPlastic** [comment]
[Debugger] Now Enabled
[JSONForMirc] Calling /JSONOpen -duw followdel https://api.twitch.tv/kraken/users/p0pbot/follows/channels/happy_meal_toy
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="init")throw new Error("JSON handler not ready");url.u="https://api.twitch.tv/kraken/users/p0pbot/follows/channels/happy_meal_toy";status="url";return"1 OK"}catch(e){error=e.message;return"0 "+error}}());
[followdel] Successfully created
[JSONForMirc] Calling /JSONUrlMethod followdel DELETE
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.m="DELETE";return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlMethod] Method set to DELETE
[JSONForMirc] Calling /JSONUrlHeader followdel Connection close
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.h.push(["Connection","close"]);return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlHeader] Header 'Connection' set to close
[JSONForMirc] Calling /JSONUrlHeader followdel Accept application/vnd.twitchtv.v3+json
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.h.push(["Accept","application/vnd.twitchtv.v3+json"]);return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlHeader] Header 'Accept' set to application/vnd.twitchtv.v3+json
[JSONForMirc] Calling /JSONUrlHeader followdel Authorization OAuth MY_OAUTH_TOKEN
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");url.h.push(["Authorization","OAuth MY_OAUTH_TOKEN"]);return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel>JSONUrlHeader] Header 'Authorization' set to OAuth MY_OAUTH_TOKEN
[JSONForMirc] Calling /JSONUrlGet followdel
[followdel>$jsTry] Executing: (function(){error=null;try{if(status!=="url")throw new Error("URL Request Not Pending");json=parse(xhr());status="done";return"1 OK"}catch(e){status="error";error=e.message;return"0 "+error}}());
[followdel] /JSONUrlGet - followdel --RAISED-- Unable to Parse: Invalid JSON
[JSONForMirc] Calling $JSON(followdel).error
[JSONForMirc] /JSONClose followdel
[followdel] Closed

**Comment by SReject** [comment]
Check your status window. The change wouldn't've added anything to the debug (you can turn it off now `/JSONDebug off` and close that window)

**Comment by Paper0rPlastic** [comment]
Unable to Parse: Invalid JSON
>> 1 >>

**Comment by SReject** [comment]
I have a suspicion as to whats going on. One more test:

alias unfollowchan {
  var %json followdel
  JSONOpen -duw %json https://api.twitch.tv/kraken/users/ $+ $lower($me) $+ /follows/channels/ $+ $lower($1)
  JSONUrlMethod %json DELETE
  JSONUrlHeader %json Connection close
  JSONUrlHeader %json Accept application/vnd.twitchtv.v3+json
  JSONUrlHeader %json Authorization OAuth $oauth
  JSONUrlGet %json
  if ($jsonerror) {
    echo -s $json(%json).error

    var %get = response.responseText.substring.length
    echo -s >> $com(JSONHandler::followdel, eval, 1, bstr, %get) >> $com(JSONHandler::followdel).result
  }
}

**Comment by Paper0rPlastic** [comment]
> Unable to Parse: Invalid JSON
>> 1 >> 2

**Comment by SReject** [comment]
Onnne last test just to be sure:

```
alias unfollowchan {
  var %json followdel
  JSONOpen -duw %json https://api.twitch.tv/kraken/users/ $+ $lower($me) $+ /follows/channels/ $+ $lower($1)
  JSONUrlMethod %json DELETE
  JSONUrlHeader %json Connection close
  JSONUrlHeader %json Accept application/vnd.twitchtv.v3+json
  JSONUrlHeader %json Authorization OAuth $oauth
  JSONUrlGet %json
  if ($jsonerror) {
    echo -s $json(%json).error

    var %get = response.responseText.substring(0,3500)
    echo -s >> $replace($com(JSONHandler::followdel).result, $cr, \r, $lf, \n, $chr(32), \s)
  }
}
```

**Comment by Paper0rPlastic** [comment]
> Unable to Parse: Invalid JSON
(double arrow) 0\sUnable\sto\sParse:\sInvalid\sJSON

**Comment by SReject** [comment]
What does this echo

```
alias unfollowchan {
  var %json followdel
  JSONOpen -duw %json https://api.twitch.tv/kraken/users/ $+ $lower($me) $+ /follows/channels/ $+ $lower($1)
  JSONUrlMethod %json DELETE
  JSONUrlHeader %json Connection close
  JSONUrlHeader %json Accept application/vnd.twitchtv.v3+json
  JSONUrlHeader %json Authorization OAuth $oauth
  JSONUrlGet %json
  if ($jsonerror) {
    echo -s $json(%json).error

    var %get = response.responseText.substring(0,3500)
    echo -s >> $com(JSONHandler::followdel, eval, 1, bstr, %get) >> $replace($com(JSONHandler::followdel).result, $cr, \r, $lf, \n, $chr(32), \s)
  }
}
```

**Comment by Dissgruntled** [comment]
> Unable to Parse: Invalid JSON
> (double arrow) 1 >>

**Comment by Paper0rPlastic** [comment]
New to this github stuff, is there a way I can post exactly what is being echoed without it triggering the quote function? lol

**Comment by SReject** [comment]
Could you run this test:

```
alias unfollowchan {
  var %json followdel
  JSONOpen -duw %json https://api.twitch.tv/kraken/users/ $+ $lower($me) $+ /follows/channels/ $+ $lower($1)
  JSONUrlMethod %json DELETE
  JSONUrlHeader %json Connection close
  JSONUrlHeader %json Accept application/vnd.twitchtv.v3+json
  JSONUrlHeader %json Authorization OAuth $oauth
  JSONUrlGet %json
  if ($jsonerror) {
    echo -s $json(%json).error

    var %get = response.responseText.length
    echo -s Call: $com(JSONHandler::followdel, eval, 1, bstr, %get) -- Length: $com(JSONHandler::followdel).result

    var %get = response.responseText.substring(0,3500)
    echo -s Call: $com(JSONHandler::followdel, eval, 1, bstr, %get) -- Text: $replace($com(JSONHandler::followdel).result, $cr, \r, $lf, \n, $chr(32), \s)
  }
}
```

**Comment by Paper0rPlastic** [comment]
ah, thanks :)

**Comment by Dissgruntled** [comment]
```
Unable to Parse: Invalid JSON
Call: 1 -- Length: 0
Call: 1 -- Text:
```

**Comment by SReject** [comment]
Mkay. The issue is that twitch is returning invalid JSON in the aspect that it is not returning anything. The JSON parser can't parse data that doesn't exist. For this use-case you can ignore this specific error by using:

```
if ($json(%json).error && $v1 !=== Unable to Parse: Invalid JSON) {
    ;; an error occurred but it wasn't due to empty JSON
}
```

As per the JSON standard raising an error for no data is the correct handling. You can test this with your browser's dev console by entering the following line:

`JSON.parse("")`

**Comment by Dissgruntled** [comment]
Ok. This is from the twitch API:

```
Example Response

204 No Content if successful.
```

The error was no big deal to me, just wanted to let you know.

**Comment by SReject** [comment]
I do appreciate it.  

In the future there's links on the main page of this project for realtime chat that may be a better place for this sort of discussion. (Gitter which is tied directly into github and uses your webbrowser, and swift which is an IRC interface)
