### ISSUE TITLE
Docs incorrect version attend

### ISSUE THREAD

**Issue by westor7** [SReject/JSON-For-Mirc#20]
In the currently stable docs (0.2.41) the downloading .mrc file is the old one and not the new.
Under the "Installation" tab of readme you should change the downloading link.

Check: https://github.com/SReject/JSON-For-Mirc/tree/v0.2.4

- Thanks!

**Comment by SReject** [comment]
This has been fixed as of commit 19e2b033add2e43cae3685e90e6139707fd56247
