### ISSUE TITLE
$longfn() may not be respond here in some hard drives

### ISSUE THREAD

**Issue by westor7** [SReject/JSON-For-Mirc#23]
I had experience a problem in the past that $longfn() didn't work correctly in some hard drives, i suggest you to use an other method there in order to find the longfn path of the file name, or using $isfile() to check if the path is vaild or something like that.

mIRC Forum post: http://forums.mirc.com/ubbthreads.php/topics/252110/westor#Post252110

Check: https://github.com/SReject/JSON-For-Mirc/blob/master/src/JSON%20For%20mIRC.mrc#L853

- Thanks!

**Comment by SReject** [comment]
Unless someone can give me an actual example of this causing issues, I believe its ok to continue using `$longfn()`.

Going to close this now, but if anyone runs into this issue, please comment.
