### ISSUE TITLE
.longfn is extra in this situation

### ISSUE THREAD

**Issue by westor7** [SReject/JSON-For-Mirc#24]
I don't think (correct me if i am wrong) the .longfn prop that needs here, as the mIRC is using the longfn directions at all since it has removed some parts that have been added for older windows versions.

mIRC Changelog: 7.44 -> 48 item

48.Changed /exit -r to no longer restart mIRC using a short filename,
   which had been necessary under older Windows versions.

Check: https://github.com/SReject/JSON-For-Mirc/blob/master/src/JSON%20For%20mIRC.mrc#L194

- Thanks!

**Comment by SReject** [comment]
I'd rather err on the side of caution with this.
