### ISSUE TITLE
Add right/left scrollbar into the Debug window

### ISSUE THREAD

**Issue by westor7** [SReject/JSON-For-Mirc#27]
I saw that missing the left-to-right and the opposite scrollbar from the debug window, that in some big data that the json logs into the window they doesn't display at all in order someone has to save the hole debug window in order to see that clearly.

E.g: https://goo.gl/cTblfa

- Thanks!

**Comment by SReject** [comment]
Making the log window a debug window did add the ability for horizontal scrollbars but adversely effected the debug window as a whole. I have reverted this change and do not believe there is a suitable solution to this issue.
