### ISSUE TITLE
Duplicate $comerr identifier in this line

### ISSUE THREAD

**Issue by westor7** [SReject/JSON-For-Mirc#29]
I saw that you have duplicate calling the $comerr identifier into this line, i am not sure that this is nessesary into this line.

Check: https://github.com/SReject/JSON-For-Mirc/blob/master/src/JSON%20For%20mIRC.mrc#L1581

- Thanks!

**Comment by SReject** [comment]
This is intentional, each `$comerr` is a check to the previous `$com` call. Its similar to doing it like:

```
if ($com(SReject/JSONForMirc/JSONShell, Error, 2, dispatch* SReject/JSONForMirc/JSONShellError) && !$comerr) {
    if ($com(SReject/JSONForMirc/JSONShellError) && $com(SReject/JSONForMirc/JSONShellError, Description, 2) && !$comerr) {
        if ($com(SReject/JSONForMirc/JSONShellError).result !== $null) {
            %Error = $v1
        }
    }
}
```
