### ISSUE TITLE
Permission to distribute.

### ISSUE THREAD

**Issue by SketchNI** [SReject/JSON-For-Mirc#42]
Hi. Sorry for filing this as an issue but I don't see any other contact details listed.

I'm looking for permission to distribute JSON-For-Mirc as part of another script that I am writing.

I will provide a link-bank to this repo and full credits to yourself for writing it.

**Comment by westor7** [comment]
This is an issue only git part, you can contact directly via these ports: http://jsonformirc.xyz/getinvolved

**Comment by SReject** [comment]
See [Distribution License](http://jsonformirc.xyz/license#distribution). In essence you may distribute your script, and then you may either:  
1. Have the user download the JSON For mIRC script  
2. Write a downloader to download the script

The reason has been discussed in other requests. Essentially non-distribution allows the end user tighter control over the scripts they have installed, what versions, etc while also prompting the user to view creditings.  

Edits: I do however make per-project decisions on distribution; if you would like to discuss it further see the get involved link @westor7 posted
