### ISSUE TITLE
Should the debugger be removed

### ISSUE THREAD

**Issue by SReject** [SReject/JSON-For-Mirc#53]
Should the debugger/logger be removed? Currently there is an extensive logger accessible via `/JSONDebug on`. The draw back of having such an extensive logger is that it slows down the script, even when disabled. Even when the messages aren't output, they are still unavoidably prepared.

In an attempt to speed up the script the debugger could be removed without losing access functionality.

**Comment by westor7** [comment]
Personally i use debug a lot when building codes related on JSON , but if it is going to be faster without it, then i suggest 2 different versions.

1. JSON-For-MIRC-Normal.mrc (without debugger)
2. JSON-For-MIRC-Full.mrc (with debugger)

I don't know , is it able to see how much speed difference is going to be in that case? with and without the debugger? any bench code to test it out?

- Thanks!

**Comment by SReject** [comment]
I won't be maintaining two copies. Its either we'll keep it or it will be removed.

As far as speed, its a decent speed increase if there's many operations at once, such as using `$JSON()` inside a `$JSONForEach()` loop

**Comment by SReject** [comment]
The debugger has been removed.
