### ISSUE TITLE
REQUEST: Proxy address

### ISSUE THREAD

**Issue by isildurum** [SReject/JSON-For-Mirc#55]
I can't seem to find anything in the docs about the use of proxy address when accessing a JSON url . 

could this be possible?

**Comment by westor7** [comment]
I don't know if you enable client proxy first (via **/proxy on** command, read more https://en.wikichip.org/wiki/mirc/commands/proxy) and then call the **/jsonopen** stuff, that may work in that case and then to use **/proxy off** to disable it.

**Comment by SReject** [comment]
JFM itself does not support the use of proxies. Internally JFM uses a windows library to make the request. This library comes from Internal Explorer, so if you can theoretically setup Internet Explorer's proxy to make use of a proxy server though I haven't tested.

A work around would be to use mIRC's `urlget` to retrieve the JSON data, and then use JFM to parse the result.
